version: '3'

services:

  init:
    image: "patrickme/stonekiller:latest"
    environment:
      - MIX_ENV=prod
      - PORT=4000
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - SECRET_KEY_BASE=d+aCKPvJQVUBO55DxXF4ni0b3r+rVtwNNGs97A90cb6BgrNJZWN08+tDYtWR4cs7
      - DATABASE_URL=ecto://postgres:postgres@database/stonekiller_dev
    volumes:
      - "./postgresql:/opt/app/postgresql"
    # command: ./initialize_database.sh
    networks:
      - backend
    depends_on:
      - postgres
  web:
    image: "patrickme/stonekiller:latest"
    ports:
      - "80:4000"
    command: mix do ecto.migrate, phx.digest, phx.server
    environment:
      - MIX_ENV=prod
      - MIX_HOST=localhost
      - LMS_HOST=localhost
      - PORT=4000
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
    networks:
      - backend
      - frontend
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    volumes:
      - "./postgresql/data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
    networks:
      - backend
networks:
  frontend:
  backend: